#ifndef EVENTS_H_
#define EVENTS_H_

#define EXIT_SERVER "EXIT_SERVER"
#define UPDATE_TEMP "UPDATE_TEMP"
#define CHANGE_DEVICE "CHANGE_DEVICE"
#define GET_GPIO_DEVICE_STATE "GET_GPIO_DEVICE_STATE"
#define SENSOR_STATES "SENSOR_STATES"

#endif