#ifndef HANDLER_H_
#define HANDLER_H_

#define  SENSOR_PRESENCA_SALA 6
#define  SENSOR_PRESENCA_COZINHA 25
#define  SENSOR_PORTA_COZINHA 21
#define  SENSOR_JANELA_COZINHA 22
#define  SENSOR_PORTA_SALA 26
#define  SENSOR_JANELA_SALA 27
#define  SENSOR_JANELA_QUARTO_1 28
#define  SENSOR_JANELA_QUARTO_2 29

#define IGNORE_CHANGE_BELOW_USEC 10000

void *deviceHandlerThread();
void sendHandlersServer();

#endif